### ISSUE TITLE
Upload Several files and CC result

### ISSUE THREAD

**Issue by lecrabe** [openforis/import_to_gee#5]
Can we upload several files at a time (in particular for SHP)
Can we have a Copy/Paste icon on the asset to copy to the clipboard ?
Can we update the necessary libraries ? e.g. (unidecode)

**Comment by 12rambau** [comment]
Split in separate issues : 

Can we upload several files at a time (in particular for SHP) ? : #3 
Can we have a Copy/Paste icon on the asset to copy to the clipboard ? #4 

Unidecode have been add by Daniel W.
